version:  '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
    working_dir: /app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    working_dir: /app
    command: sh -c "npm run start:dev"
    ports:
      - "8080:8080"
